### ISSUE TITLE
Why is "Tench chance" a thing?

### ISSUE THREAD

**Issue by RobertLeeMich** [H4waiianPunch/Pearl-Luck-Tracker#17]
The wiki doesn't say that your Golden Tench chance increases with each fish caught, so why is this a stat on the plugin? This isn't how RNG works, much less a 1/20,000 chance.

Also I'm fairly sure the last pearl/dry numbers aren't working either. Confirmed the Last Pearl and Longest dry aren't working as I got a pearl at 810 pearls now and the number didn't change, unless I'm misunderstanding the stat.

Golden Tench Wiki entry: https://oldschool.runescape.wiki/w/Golden_tench

Edit: The "Tench chance" is just inaccurate, ain't no way there's a 3.6% chance at 330 fish. Each click is a 1 in 20k chance to get a gold tench no matter what, there's no "aggregating it". Anyway, not gonna use this plugin, this topic can be closed.

**Comment by H4waiianPunch** [comment]
Hi Robert,

The tench chance on the first iteration(the one currently live) increases the % by .1 for every 20 fish caught. While yes, this isn't how RNG works, I thought it would be a fun stat to include for a users session of doing Aerial Fishing.

As for longest dry: This will keep track of the highest number of fish it took to catch a pearl. 

Last Pearl shows you how many fish it took to catch your most recent pearl.

I understand you said you won't be using the plugin, and I understand. Thanks for taking a look into it anyway, maybe when the new version comes out, hopefully soon. You'll give it another shot.
