### ISSUE TITLE
Show custom Molch Pearl chance

### ISSUE THREAD

**Issue by Koslas1** [H4waiianPunch/Pearl-Luck-Tracker#7]
Maybe have a config option to show the droprate you have for a molch pearl?
Which the current equation is to work that out is
1 / (100 - ((X - 40) * 25 / 59))
Where
X = (FishingLevel * 2 + HunterLevel) / 3

This would be something like how the maths works for it, I'm unsure how to do some things, such as pulling fishing levels and hunter levels from RuneLite

`public class DropRateCalculator {

    public static void main(String[] args) {
        int fishingLevel = // Get Fishing level from RuneLite
        int hunterLevel = // Get Hunter level from RuneLite

        double X = (fishingLevel * 2 + hunterLevel) / 3.0;
        double dropRate = 100 - (((X - 40) / 59) * 25);
        int roundedDropRate = (int) Math.ceil(dropRate);
    }
}
`

And now make a setting in the config if you want to show the droprate or not, and update the fishingLevel and hunterLevel if possible when leveling up.
Then if the setting is enabled show something in the overlay like Pearl Droprate: 1/ roundedDropRate

**Comment by H4waiianPunch** [comment]
Hmm, looks like you did a good bit of the heavy lifting there for me which is great!

I'll look to do try this over the weekend and see if I can't get it working. I like it as being a config option to show or not as well.

**Comment by Koslas1** [comment]
Another suggestion which you could add as config options aswell, since you're obviously keeping track of the amount caught, because of the tench chance, since you have the worst dry streak (Mine was 329 when I was using it earlier and I worked out my drop rate to be 1/79 😥) you could maybe even have a best streak (Which mine was 2) and then fish caught / pearlsGained for your average rate so if I caught 2,200 fish and gained 32 pearls with that bad dry streak and also the good streaks I was getting a pearl on average of 1/68.75 catches, therefore I was actually a bit luckier than the 1/79 droprate, and preferably having these options to be enabled/disabled in the settings.
Aswell as maybe even making the last caught, and worst dry streak as options so if I wanted I could just see my best and worst streaks, or just my average rate etc.
But so far with me using it, I do love the plugin already, thanks for making it, I wouldn't know where to start with it.

And I mainly gave you the example before so you had the correct maths (Which is from the wiki, quoted from a Mod Ash Tweet)

**Comment by BugcatcherBill** [comment]
@H4waiianPunch can I get permissions to push a remote branch and open a PR? I'm getting a 403 when I attempt to push it up. It accounts for this request and a bit more. You are also free to reject it obviously if its not what you are looking for.

**Comment by H4waiianPunch** [comment]
Hey @BugcatcherBill , I'm nearly done with everything, just working on the Tench Chance right now and then I'm pushing everything out together. Sorry I'm being restrictive on pushing, etc. It's just my first plugin and my opportunity to learn how to make it work myself. I know that goes against the grain for what most people would do, but I'm weird I guess lol.

**Comment by H4waiianPunch** [comment]
Finally pushed everything to master, I'll push to RL soon.



> No worries, take your time. This is actually my first attempt at contributing as well. Its mostly driven by trying to make aerial fishing a bit less boring lol. I was a bit disappointed there was such little plugin support for aerial fishing and was excited when I came across your plugin. Definitely appreciate this as your project and learning opportunity. If you are looking for open collaboration please add that permission to the repo after you finish pushing up your changes. I will resolve any conflicts and determine if my PR adds anything of value in addition to what you have done.

I'll figure out how to loosen things up a bit, I went with the strictest settings because idk Github that well. 

> The permission will allow me to push my branch up so that you can look at the code and decide if you want to accept it or not. If you would prefer this repo to remain private that's okay too. But at the very least I would like to share the code with you. Its also a great opportunity to review each other's code and learn together.

I think you're right. I was being a dink about it. Reviewing the code and learning is always important.

> 
> If you are 100% against even that. I understand just lmk and I will just run my version locally and leave you alone :)

Don't leave me alone, I was being stupid lol. I'll figure out how to set things up nicer in the coming days and then we'll go from there!

**Comment by BugcatcherBill** [comment]
Sounds like a plan, Love the changes that I have seen in the read me so far.  I prefer % over "x/y" format, but it looks like largely we approached this pretty similarly.

![image](https://github.com/user-attachments/assets/fd8ac75e-ff0c-4f52-913c-2ccca14be8c6)
A little splash of color might not be a bad idea either :)

**Comment by H4waiianPunch** [comment]
Nice! Very similar overall I would say! 
Love the colors, but I wanted to try and keep the same things grouped together color-wise, thought it might be easier to read.

Also enjoying the longer descriptions for the overlay, might need to change some of those around to be more descriptive like yours. I just worry about taking up too much real estate on the screen for users.

Since I have the PR to the plugin hub on-going I'll close this out.

**Comment by H4waiianPunch** [comment]
> @H4waiianPunch can I get permission to push a remote branch and open a PR? I'm getting a 403 when I attempt to push it up. It accounts for some of this request and maybe a bit more.

PS. Try again. @BugcatcherBill

**Comment by BugcatcherBill** [comment]
> > @H4waiianPunch can I get permission to push a remote branch and open a PR? I'm getting a 403 when I attempt to push it up. It accounts for some of this request and maybe a bit more.
> 
> PS. Try again. @BugcatcherBill

Still denied
![image](https://github.com/user-attachments/assets/a6a4b162-0e1d-4a64-b604-3af22577c8d1)
