### ISSUE TITLE
Best Streak and additional toggleables

### ISSUE THREAD

**Issue by H4waiianPunch** [H4waiianPunch/Pearl-Luck-Tracker#8]
Another suggestion which you could add as config options aswell, since you're obviously keeping track of the amount caught, because of the tench chance, since you have the worst dry streak (Mine was 329 when I was using it earlier and I worked out my drop rate to be 1/79 😥) you could maybe even have a best streak (Which mine was 2) and then fish caught / pearlsGained for your average rate so if I caught 2,200 fish and gained 32 pearls with that bad dry streak and also the good streaks I was getting a pearl on average of 1/68.75 catches, therefore I was actually a bit luckier than the 1/79 droprate, and preferably having these options to be enabled/disabled in the settings.
Aswell as maybe even making the last caught, and worst dry streak as options so if I wanted I could just see my best and worst streaks, or just my average rate etc.
But so far with me using it, I do love the plugin already, thanks for making it, I wouldn't know where to start with it.

And I mainly gave you the example before so you had the correct maths (Which is from the wiki, quoted from a Mod Ash Tweet)

_Originally posted by @Koslas1 in https://github.com/H4waiianPunch/Pearl-Luck-Tracker/issues/7#issuecomment-2450847858_

**Comment by Koslas1** [comment]
Also to add onto this, you could also have another option to show total molch pearls gained (And maybe how many tenchs have been caught), and also an dropdown menu of when to reset stats with some options as "Session" meaning when the bird leaves your hand, "Logout" or "Never" maybe even a reset stats button (Unless the standard Reset button would wipe your stats), and preferably keep tracking the stats when they are disabled, so if someone decides to enable them, it will know the current stuff, such as if I wanted to quickly check how many pearls I've gained, I can turn the option to display them on and then off.

**Comment by H4waiianPunch** [comment]
Some of that logic doesn't seem like it would be too difficult, the total pearls gained for example, but the reset logic would probably cause me a big headache as I suspect it might require a larger code restructure. 

For sure:
- Total Molch pearls
- Total Golden Tench

Maybe:
- Allow users to choose their reset option
- - Currently set to session for all variables except dryStreak

**Comment by Koslas1** [comment]
Yeah, I'm not sure how big of the my suggestions are, however they are just suggestions :) I may have to get back into Java and maybe help out and do a pull request

**Comment by BugcatcherBill** [comment]
A huge value add for me is to keep "total" stats in addition to session stats. If those total stats were able to be manually reset would that be sufficient for your ask @Koslas1 ?

I have a few of those working and plan on submitting a PR soon.

**Comment by H4waiianPunch** [comment]
I have an update coming out soon that address most things, I've also included some new variables etc.

**Comment by BugcatcherBill** [comment]
Cool, I will wait on that then. Appreciate the update!

**Comment by H4waiianPunch** [comment]
I've merged my changes into master finally, sorry it took so long gents. Going to get it pushed over to RL here soon.

**Comment by H4waiianPunch** [comment]
Since I have the on-going PR with the plugin hub, I'm going to close this out.
