### ISSUE TITLE
Clarification on Tench chance and Don't hover me please

### ISSUE THREAD

**Issue by Koslas1** [H4waiianPunch/Pearl-Luck-Tracker#9]
Would you be able to clarify what the tench chance is showing? Is it showing the % of how much towards droprate I am at? For example on 10,000 catches, would that show 50% as that's half of the droprate of 20,000?
As you have 50% of getting 1 tench 13,862-13,863 (49.99850735%-50.00100743%) of getting a tench. You can see what I mean with this [wiki calculator](https://oldschool.runescape.wiki/w/Calculator:Dry_calc)
If you were able to, you could maybe even have this as an option to change what type of percentage it shows.

Also could you explain what the Don't hover me please text box is used for? Or does it do nothing at all?

**Comment by H4waiianPunch** [comment]
I can certainly provide some clarification.

- The tench chance gets updated by .1% for every 20 fish caught. So if you've caught 10000 fish, it should show at 50%.
- I had tried to get it to show a more accurate number but there were issues with rounding I was noticing. 
- The way I looked at this alert is if I've caught 10000 fish, I'm at the halfway mark and "should have" a 50% chance to have gotten a golden tench. So while not as accurate as the wiki calculator, I still think it's a fun little stat to look at.

- The don't hover me please text box was just me wanting to meme really. I guess I should get rid of it though as it serves no purpose.

**Comment by Koslas1** [comment]
So the tench chance is just what % you are to being on droprate, not the actual chance? I could maybe see if I could sort out the maths formula for it, and help you with that

**Comment by H4waiianPunch** [comment]
> So the tench chance is just what % you are to being on droprate, not the actual chance?

That's correct. I just wanted to keep it pretty simple and not do a bunch of math on it really. Something to look at in the future if more people want a more accurate drop rate chance. For now I'll hold off on it.
